### ISSUE TITLE
Citizens Armor bug

### ISSUE THREAD

**Issue by Serpano** [HurricanKai/Blacksmith#15]
Hello dear people,
Anyone of you Should surely know Citizens?
There is a tool (addon) called BlackSmith.

Source: https://wiki.citizensnpcs.co/Blacksmith

The following problem for a player:
He can weapons and repair tools but if he wants to fix a broken Iron Leggings there by right click this is tightened immediately.
And the NPC reports this is not the part is what you want to get fixed.
In order to do that, the armor part has to stay in the hand now it does not
If you make a right click it will be put on.

Sry for my bad english i hope you understand my problem i come from germany

Minecraft: 1.11.2
Citizens Version: Citizens v2.0.22-SNAPSHOT (build 1481)

**Comment by HurricanKai** [comment]
hello, im from germany to, your english is fine.
this issue already exists see #4 
thanks for the report!
